package com.zutubi.prototype.annotation;

import com.zutubi.pulse.prototype.FieldType;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)

// Annotation handler reference that is used to process 'this' annotation.
@Handler(TypeSelectAnnotationHandler.class)

// This annotation is a form field of type SELECT.
@Field(type = FieldType.SELECT)

/**
 * The TypeSelect annotation generates a form select widget using the defined extensions
 * of the configurationType as the source for the select options.
 *
 * @see @com.zutubi.prototype.annotation.Select()
 */
public @interface TypeSelect
{
    /**
     * The configuration type used to generate the type select options.  The actual option list will be
     * generated by the types that have been registered as 'extensions' of this configuration type.
     * 
     * @return
     */
    Class configurationType();

    public static final int DEFAULT_size = 0;

    /**
     * The number of options that are visible.
     *
     * @return
     */
    public int size() default DEFAULT_size;
}
