/* Copyright 2017 Zutubi Pty Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.zutubi.pulse.master.scheduling;

import com.zutubi.util.bean.ObjectFactory;
import com.zutubi.util.logging.Logger;

import java.util.HashSet;
import java.util.Set;

/**
 * The default trigger handler handles the details of firing a trigger.
 *
 * This trigger handler ensures that a trigger can only be firing once,
 * and all trigger attempts that are raised whist the trigger is already
 * executing its task are dropped.
 */
public class DefaultTriggerHandler implements TriggerHandler
{
    private static final Logger LOG = Logger.getLogger(DefaultTriggerHandler.class);

    private ObjectFactory objectFactory;

    private final Set<String> executingTriggers = new HashSet<String>();

    public void fire(Trigger trigger) throws SchedulingException
    {
        TaskExecutionContext context = new TaskExecutionContext();
        fire(trigger, context);
    }

    public void fire(Trigger trigger, TaskExecutionContext context) throws SchedulingException
    {
        // do we want to execute this task?
        String triggerKey = trigger.getName() + ":" + trigger.getGroup();
        synchronized(executingTriggers)
        {
            if (executingTriggers.contains(triggerKey))
            {
                LOG.info("Request to fire trigger '" + triggerKey + "' ignored since the trigger is already firing.");
                return;
            }
            LOG.info("executing trigger " + triggerKey);
            executingTriggers.add(triggerKey);
        }

        try
        {
            context.setTrigger(trigger);
            trigger.fire();

            // determine the task to be executed.
            try
            {
                Task task = objectFactory.buildBean(trigger.getTaskClass());
                task.execute(context);
            }
            catch (Exception e)
            {
                // the transaction will still commit if a schedulingException is
                // thrown because it is declared in the method definition.
                LOG.severe("Uncaught exception generated by execution of trigger "+triggerKey+".", e);
                throw new SchedulingException(e);
            }
            catch (Throwable t)
            {
                // the transaction will still commit if a schedulingException is
                // thrown because it is declared in the method definition.
                LOG.severe("Uncaught throwable generated by execution of trigger "+triggerKey+".", t);
                throw new SchedulingException(t);
            }
        }
        finally
        {
            synchronized(executingTriggers)
            {
                if (!executingTriggers.remove(triggerKey))
                {
                    LOG.error("failed to remove trigger key from set.");
                }
                else
                {
                    LOG.info("finished trigger " + triggerKey);
                }
            }
        }
    }

    public void setObjectFactory(ObjectFactory objectFactory)
    {
        this.objectFactory = objectFactory;
    }
}
