package com.zutubi.pulse.master.scheduling;

import com.zutubi.pulse.master.model.persistence.TriggerDao;
import com.zutubi.util.bean.ObjectFactory;
import com.zutubi.util.logging.Logger;

import java.util.HashSet;
import java.util.Set;

/**
 * The default trigger handler handles the details of firing a trigger.
 *
 * This trigger handler ensures that a trigger can only be firing once,
 * and all trigger attempts that are raised whist the trigger is already
 * executing its task are dropped.
 */
public class DefaultTriggerHandler implements TriggerHandler
{
    private static final Logger LOG = Logger.getLogger(DefaultTriggerHandler.class);

    private ObjectFactory objectFactory;
    private TriggerDao triggerDao;

    private final Set<String> executingTriggers = new HashSet<String>();

    public void fire(Trigger trigger) throws SchedulingException
    {
        TaskExecutionContext context = new TaskExecutionContext();
        fire(trigger, context);
    }

    public void fire(Trigger trigger, TaskExecutionContext context) throws SchedulingException
    {
        // hack: need to handle the transactional nature of the runtime environment better.
        if (trigger.isPersistent())
        {
            trigger = triggerDao.findById(trigger.getId());
        }

        // do we want to execute this task?
        String triggerKey = trigger.getName() + ":" + trigger.getGroup();
        synchronized(executingTriggers)
        {
            if (executingTriggers.contains(triggerKey))
            {
                LOG.info("Request to fire trigger '" + triggerKey + "' ignored since the trigger is already firing.");
                return;
            }
            LOG.info("executing trigger " + triggerKey);
            executingTriggers.add(triggerKey);
        }

        try
        {
            context.setTrigger(trigger);
            trigger.fire();

            // determine the task to be executed.
            try
            {
                Task task = objectFactory.buildBean(trigger.getTaskClass());
                task.execute(context);
            }
            catch (Exception e)
            {
                // the transaction will still commit if a schedulingException is
                // thrown because it is declared in the method definition.
                LOG.severe("Uncaught exception generated by execution of trigger "+triggerKey+".", e);
                throw new SchedulingException(e);
            }
            catch (Throwable t)
            {
                // the transaction will still commit if a schedulingException is
                // thrown because it is declared in the method definition.
                LOG.severe("Uncaught throwable generated by execution of trigger "+triggerKey+".", t);
                throw new SchedulingException(t);
            }
        }
        finally
        {
            synchronized(executingTriggers)
            {
                if (!executingTriggers.remove(triggerKey))
                {
                    LOG.error("failed to remove trigger key from set.");
                }
                else
                {
                    LOG.info("finished trigger " + triggerKey);
                }
            }
        }
    }

    public void setObjectFactory(ObjectFactory objectFactory)
    {
        this.objectFactory = objectFactory;
    }

    public void setTriggerDao(TriggerDao triggerDao)
    {
        this.triggerDao = triggerDao;
    }
}
