package com.zutubi.pulse.restore;

import com.zutubi.pulse.test.PulseTestCase;
import com.zutubi.pulse.util.FileSystemUtils;
import com.zutubi.util.IOUtils;

import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.Calendar;
import java.util.Properties;

/**
 *
 *
 */
public class ArchiveFactoryTest extends PulseTestCase
{
    private ArchiveFactory factory;

    private File tmp;
    private File importDir;
    private File exportDir;

    protected void setUp() throws Exception
    {
        super.setUp();

        tmp = FileSystemUtils.createTempDir();
        factory = new ArchiveFactory();
        exportDir = new File(tmp, "export");
        importDir = new File(tmp, "import");
        factory.setArchiveDirectory(exportDir);
        factory.setTmpDirectory(importDir);
    }

    protected void tearDown() throws Exception
    {
        removeDirectory(tmp);
        tmp = null;
        exportDir = null;
        importDir = null;
        
        super.tearDown();
    }

    public void testCreateNewExpandedDirectoryArchive() throws ArchiveException
    {
        // specify the location for new archives.

        // create a new archive.
        // -- names are automatically generated by archive name generator, looks at directory into which
        //    the archive will be created and does the rest.

        Date bc = Calendar.getInstance().getTime();

        Archive createdArchive = factory.createArchive();

        Date ac = Calendar.getInstance().getTime();

        assertNotNull(createdArchive.getCreated());       // ensure that the date is within the appropriate bounds.
        assertNotNull(createdArchive.getVersion());       

        assertNotNull(createdArchive.getBase());
        assertTrue(createdArchive.getBase().exists());

        assertEquals(importDir, createdArchive.getBase().getParentFile());
        assertNull(createdArchive.getOriginal());
    }

    public void testExportArchive() throws ArchiveException
    {
        Archive archive = factory.createArchive();
        File exportedZipFile = factory.exportArchive(archive);
        
        assertNotNull(exportedZipFile);
        assertEquals(exportDir, exportedZipFile.getParentFile());
    }

    public void testArchivingDataRoundTrip() throws ArchiveException, IOException
    {
        Archive archive = factory.createArchive();
        File archiveBase = archive.getBase();

        createSampleDataFile(new File(archiveBase, "sample.txt"));

        File zip = factory.exportArchive(archive);

        Archive importedArchive = factory.importArchive(zip);

        assertNotSame(archive.getBase(), importedArchive.getBase());
        assertTrue(new File(importedArchive.getBase(), "sample.txt").isFile());
    }
    
    private void createSampleDataFile(File dataFile) throws IOException
    {
        if (!dataFile.exists() && !dataFile.createNewFile())
        {
            throw new IOException();
        }
        IOUtils.write(new Properties(), dataFile);
    }
}
