package com.zutubi.pulse.master.restore;

import java.io.File;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Calendar;

/**
 * An implementation of the name generator that uses a date stamp to
 * uniquely name the archive file.
 */
public class UniqueDatestampedNameGenerator implements ArchiveNameGenerator
{
    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd_hh-mm-ss");

    /**
     * Generate a unique filename for an archive file that will be placed into the target directory.
     *
     * @param target directory into which the archive file will be placed.
     *
     * @return the generated file name.
     */
    public String newName(File target)
    {
        String candidateName = "archive-" + DATE_FORMAT.format(Calendar.getInstance().getTime()) + ".zip";
        File candidate = new File(target, candidateName);
        int i = 1;
        while (candidate.isFile())
        {
            candidate = new File(target, candidate + "_" + i + ".zip");
            i++;
        }
        return candidate.getName();
    }

    /**
     * Returns true if the specified name matches the format of the names generated
     * by this name generator.
     *
     * @param name the name to be checked.
     *
     * @return true if the name could have been generated by this generator, false otherwise.
     */
    public boolean matches(String name)
    {
        if (!name.startsWith("archive-"))
        {
            return false;
        }
        if (!name.endsWith(".zip"))
        {
            return false;
        }
        name = name.substring(8, name.length() - 4);
        try
        {
            DATE_FORMAT.parse(name);
            return true;
        }
        catch (ParseException e)
        {
            return false;
        }
    }
}
