package com.zutubi.pulse.master.webwork.dispatcher.mapper.browse;

import com.zutubi.pulse.master.webwork.dispatcher.mapper.ActionResolver;
import com.zutubi.pulse.master.webwork.dispatcher.mapper.ActionResolverSupport;

import java.util.Arrays;
import java.util.List;

/**
 * Maps to artifacts generated by a single build stage.
 */
public class StageArtifactsActionResolver extends ActionResolverSupport
{
    private boolean raw;

    public StageArtifactsActionResolver(String stage, boolean raw)
    {
        super("viewBuildArtifacts");
        addParameter("stageName", stage);
        this.raw = raw;
    }

    public List<String> listChildren()
    {
        return Arrays.asList("<command>");
    }

    public ActionResolver getChild(String name)
    {
        return new CommandArtifactsActionResolver(name, raw);
    }
}
