/* Copyright 2017 Zutubi Pty Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.zutubi.pulse.master.webwork.dispatcher.mapper.browse;

import com.zutubi.pulse.master.webwork.dispatcher.mapper.ActionResolver;
import com.zutubi.pulse.master.webwork.dispatcher.mapper.ActionResolverSupport;

import java.util.Arrays;
import java.util.List;

/**
 * Maps to artifacts generated by a single build stage.
 */
public class StageArtifactsActionResolver extends ActionResolverSupport
{
    private boolean raw;

    public StageArtifactsActionResolver(String stage, boolean raw)
    {
        super("viewBuildArtifacts");
        addParameter("stageName", stage);
        this.raw = raw;
    }

    public List<String> listChildren()
    {
        return Arrays.asList("<command>");
    }

    public ActionResolver getChild(String name)
    {
        return new CommandArtifactsActionResolver(name, raw);
    }
}
