package com.zutubi.events;

import com.zutubi.util.logging.Logger;

import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * An event dispatcher that dispatches events on a separate thread to the thread
 * on which the event was raised.
 */
public class AsynchronousDispatcher implements EventDispatcher
{
    private static final Logger LOG = Logger.getLogger(AsynchronousDispatcher.class);

    private final ExecutorService executor;

    public AsynchronousDispatcher()
    {
        executor = Executors.newSingleThreadExecutor();
    }

    public void dispatch(final Event evt, final List<EventListener> listeners)
    {
        executor.execute(new Runnable()
        {
            public void run()
            {
                for (EventListener listener: listeners)
                {
                    try
                    {
                        listener.handleEvent(evt);
                    }
                    catch (Exception e)
                    {
                        // isolate the exceptions generated by the event handling.
                        evt.addException(e);
                        LOG.warning("Exception generated by " + listener + ".handleEvent(" + evt + ")", e);
                    }
                }
            }
        });
    }
}
