package com.zutubi.events;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * An event dispatcher implementation that uses the thread on which the event was published to dispatch to the listeners.
 */
public class SynchronousDispatcher implements EventDispatcher
{
    private static final Logger LOG = Logger.getLogger(SynchronousDispatcher.class.getName());

    public void dispatch(Event evt, List<EventListener> listeners)
    {
        for (EventListener listener : listeners)
        {
            try
            {
                listener.handleEvent(evt);
            }
            catch (Exception e)
            {
                // isolate the exceptions generated by the event handling.
                evt.addException(e);
                LOG.log(Level.WARNING, "Exception generated by " + listener + ".handleEvent(" + evt + ")", e);
            }
        }
    }
}
