package com.zutubi.pulse.core.dependency.ivy;

import com.zutubi.util.logging.Logger;
import org.apache.ivy.util.Message;

/**
 * An adapter that allows us to direct log output generated by ivy to our own
 * logging system.
 */
public class IvyMessageLoggerAdapter extends org.apache.ivy.util.AbstractMessageLogger
{
    private static final Logger LOG = Logger.getLogger(IvyMessageLoggerAdapter.class);

    protected void doProgress()
    {
        // This is just the default logger.  This logger will not be used for actions that
        // provide progress feedback.
    }

    protected void doEndProgress(String msg)
    {
        // This is just the default logger.  This logger will not be used for actions that
        // provide progress feedback.
    }

    public void log(String msg, int level)
    {
        // send the message logging to one of our loggers.
        switch (level)
        {
            case Message.MSG_DEBUG:
                LOG.debug(msg);
                break;
            case Message.MSG_ERR:
                LOG.error(msg);
                break;
            case Message.MSG_INFO:
                LOG.info(msg);
                break;
            case Message.MSG_VERBOSE:
                LOG.finest(msg);
                break;
            case Message.MSG_WARN:
                LOG.warning(msg);
                break;
        }
    }

    public void rawlog(String msg, int level)
    {
        log(msg, level);
    }
}
