package com.zutubi.pulse.core.dependency.ivy;

import com.zutubi.util.logging.Logger;
import org.apache.ivy.util.Message;

/**
 * An adapter that allows us to direct log output generated by ivy to our own
 * logging system.
 */
public class IvyMessageLoggerAdapter extends org.apache.ivy.util.AbstractMessageLogger
{
    private Logger delegate = null;

    public IvyMessageLoggerAdapter(Logger delegate)
    {
        this.delegate = delegate;
    }

    protected void doProgress()
    {
        // we do not show progress at the moment.
    }

    protected void doEndProgress(String msg)
    {
        // we do not show progress at the moment.
    }

    public void log(String msg, int level)
    {
        // send the message logging to one of our loggers.
        switch (level)
        {
            case Message.MSG_DEBUG:
                delegate.debug(msg);
                break;
            case Message.MSG_ERR:
                delegate.error(msg);
                break;
            case Message.MSG_INFO:
                delegate.info(msg);
                break;
            case Message.MSG_VERBOSE:
                delegate.finest(msg);
                break;
            case Message.MSG_WARN:
                delegate.warning(msg);
                break;
        }
    }

    public void rawlog(String msg, int level)
    {
        log(msg, level);
    }
}
