package com.zutubi.pulse.core.plugins;

import com.zutubi.pulse.core.test.TestUtils;
import com.zutubi.pulse.core.test.api.PulseTestCase;
import com.zutubi.util.FileSystemUtils;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;

public abstract class BasePluginSystemTestCase extends PulseTestCase
{
    protected File tmpDir;
    
    protected ConfigurablePluginPaths paths;
    protected PluginManager manager;

    protected void setUp() throws Exception
    {
        super.setUp();

        // base directory will be cleaned up at the end of the test.
        tmpDir = FileSystemUtils.createTempDir(PluginManagerTest.class.getName(), "");

        File internalDir = new File(tmpDir, "internal");
        assertTrue(internalDir.mkdirs());
        File prepackagedDir = new File(tmpDir, "prepackaged");
        assertTrue(prepackagedDir.mkdirs());

        File storageDir = new File(tmpDir, "storage");
        assertTrue(storageDir.mkdirs());
        File configDir = new File(tmpDir, "config");
        assertTrue(configDir.mkdirs());
        File workDir = new File(tmpDir, "work");
        assertTrue(workDir.mkdirs());

        File osgiDir = new File(tmpDir, "osgi");
        assertTrue(osgiDir.mkdirs());

        paths = new ConfigurablePluginPaths();
        paths.setPrepackagedPluginStorageDir(prepackagedDir);
        paths.setInternalPluginStorageDir(internalDir);
        paths.setOsgiConfigurationDir(osgiDir);
        paths.setPluginRegistryDir(configDir);
        paths.setPluginStorageDir(storageDir);
        paths.setPluginWorkDir(workDir);

        // copy contents from etc osgi into temp osgi dir.
        FileSystemUtils.copy(osgiDir, new File(TestUtils.getPulseRoot(), "com.zutubi.pulse.master/etc/osgi").listFiles(new FileFilter()
        {
            public boolean accept(File file)
            {
                return !file.isDirectory();
            }
        }));
    }

    protected void tearDown() throws Exception
    {
        shutdownPluginCore();
        removeDirectory(tmpDir);

        super.tearDown();
    }

    protected void installPulseInternalBundles() throws IOException
    {
        // this path does not exist since it is generated by refresh.plugins..., not available in a newly checked out version of pulse.
        String internalPath = FileSystemUtils.composeFilename("plugins", "internal");
        FileSystemUtils.copy(paths.getInternalPluginStorageDir(), new File(TestUtils.getPulseRoot(), internalPath));
    }

    protected void restartPluginCore() throws Exception
    {
        shutdownPluginCore();
        startupPluginCore();
    }

    protected void startupPluginCore() throws PluginException
    {
        try
        {
            manager = new PluginManager();
            manager.setPluginPaths(paths);
            manager.init();
        }
        catch (Exception e)
        {
            throw new PluginException(e);
        }
    }

    protected void shutdownPluginCore() throws Exception
    {
        if (manager != null)
        {
            try
            {
                manager.destroy();
            }
            catch (Exception e)
            {
                fail(e.getMessage());
            }
            manager = null;
        }
    }
}
